config/routes.rb
Rails.application.routes.draw do
  
  get  'signup' => 'users#new'
  resources :users
  resources :produtos
  root 'pages#home'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'sobre' => 'pages#sobre'
  delete 'destroy' => 'users#destroy'
  get 'ajuda' =>'pages#ajuda'
  get 'produtos' => 'pages#produtos'

end

app/models/produto.rb
class Produto < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :conteudo, presence: true,

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :produtos
	before_save {self.email = email.downcase}
	validates :name, presence: true, length: {maximum: 50}
	validates :email, presence: true, length: {maximum: 255}, 
	uniqueness: {case_sensitive: false}
								  
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def sobre
  end

  def ajuda
  end

  def produtos
  end

end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
  	usuario = User.find_by(email:params[:session][:email].downcase)
  	if usuario && usuario.authenticate(params[:session][:password])
  		login usuario
  		redirect_to usuario
  	else
  		render 'new'
  	end
  end

  def destroy
    logout if logged_in?
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:index,:edit, :update]
    before_action :correct_user,   only: [:edit, :update]
    before_action :admin_user,     only: :destroy
    def index
      @users = User.all
    end

  def show
    @user = User.find(params[:id])
  end
  def new
  	@user = User.new
  end
  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "Sua conta foi criada com sucesso!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end
    def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end


  private
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

     def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless usuario_atual?(@user)
    end

 def admin_user
      redirect_to(root_url) unless usuario_atual.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def titulo(pag_titulo = '')
    titulo = "Play.Market"
    if pag_titulo.empty?
      titulo
    else
      pag_titulo + " | " + titulo
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	#Loga o usuario passado
	#session = metodo do Rails que ajuda a realizar log in
	def login(user)
		session[:id_usuario] = user.id
	end
	def usuario_atual
    if (id_usuario = session[:id_usuario])
    		
   	@usuario_atual = @usuario_atual || User.find_by(id: session[:id_usuario])
   end
  	end

  	def usuario_atual?(user)
  		user == usuario_atual
  	end

  	def logged_in?
    !usuario_atual.nil?
 	end

 	def logout
 		session.delete(:id_usuario)
 		@usuario_atual = nil
 	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_cabecalho.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Play.Market", root_path , id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Ajuda",  ajuda_path%></li>
            <% if logged_in? %>
          <li><%= link_to "Users", users_path  %></li>
          <li><%= link_to "Produtos", produtos_path  %></li>
              <li><%= link_to "Profile", usuario_atual %></li>
              <li><%= link_to "Configuracoes", edit_user_path(usuario_atual) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li> 
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>

          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Play.Market</title>
   <title><%= titulo(yield(:title)) %> | Play.Market
   </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/cabecalho' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/ajuda.html.erb
<html>
  <head>
  </head>
  <body>
    <h1>Ajuda</h1>
    <p> Para ter acesso ao conteudo da Play.Market, o usuario precisa estar conectado na Play.Market. </p>
    <p> Para se conectar, o usuario precisa criar uma conta atraves do link <%= link_to "Cadastre-se agora!", signup_path, id: "signup" %> na pagdina inicial da Play.Market. </p>
    <p> Possuindo uma conta na Play.Market, o usuario ja pode se conectar atraves da pagina <%= link_to "Login", login_path, id: "signup" %> </p>
  </body>
</html>

app/views/pages/home.html.erb
<html>
  <head>
    <title><%= yield(:title) %> | Play.Market</title>
  </head>
  <body>
    <div class="center jumbotron">
  <h1>Play.Market</h1>

  <h2>
    Essa e a pagina inicial da Play.Market, o melhor comercio digital de jogos do Brasil.
  </h2>

  <%= link_to "Cadastre-se agora!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
  </body>
</html>

app/views/pages/sobre.html.erb
<html>
  <head>
    <title>Sobre | Play.Market</title>
  </head>
  <body>
    <h1>Sobre</h1>
  </body>
</html>

app/views/produtos/_produto.html.erb
<li id="produto-<%= produto.id %>">
  <span class="user"><%= link_to produto.user.name, produto.user %></span>
  <span class="conteudo"><%= produto.content %></span>
  </span>
</li>

app/views/produtos/show.html.erb
<h1></h1>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

<p>Nome: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
      <%= link_to user.name, user %>
        <% if usuario_atual.admin? && !usuario_atual?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "Quer realmente deletar?" } %>
  <% end %>

    </li>

app/views/users/edit.html.erb
<h1>Atualize seu Perfil</h1>
<% provide(:title, 'Atualize seu Perfil') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
      <%= f.label :name, "Nome", id: "labels" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, id: "labels" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, id: "labels" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation", id: "labels" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Atualizar", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Todos os usuarios</h1>

<ul class="users">
  <%=render @users%>
</ul>

app/views/users/new.html.erb
<h1>Cadastro</h1>
<% provide(:title, 'Cadastre-se') %>
<h2>Cadastre-se abaixo</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
      <%= f.label :name, "Nome", id: "labels" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "Email", id: "labels" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "Senha", id: "labels" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Senha novamente", id: "labels" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1></h1>

<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

<p>Nome: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>